### ISSUE TITLE
How rebuild android apk after dexprotector ?

### ISSUE THREAD

**Issue by aleks921** [strazzere/android-lkms#1]
I get new.apk and libdexprotector.so uses android-lkms tool. But how me build apk file ? I try all smali with *.so recompile succesfull, but when apk running. This apk don't see native methods in library and fail.

**Comment by strazzere** [comment]
I'm not sure what you're attempting to do, however this method isn't meant to explicitly strip protections for use of rebuilding the application. It merely lets you get a raw form to reverse engineer.
